### ISSUE TITLE
注册时需要传入头像，性别，性取向的字段---  默认头像地址有误，不需要加入assets

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/dongzhenai#13]
![2018-04-20 15-49-03屏幕截图.png](https://images.zenhubusercontent.com/5ab4524a4b5806bc2bcc0bd5/d7989ce8-d8ee-48b6-8dbd-c31fc173adce)

**Comment by ivanzhang2** [comment]
这个问题，彭聪可以后面看看，没问题就关了

**Comment by pengconguses1** [comment]
这个没问题了 高就该关了  关晚了
